---
title: "tracking_sheets"
author: "MUVA"
date: "18/01/2022"
output: 
  word_document:
    reference_docx: table.docx
    toc: true
---

```{r setup, include=FALSE}
library(rio)
library(dplyr)
library(gt)
knitr::opts_chunk$set(echo = TRUE)


dir_fp_sample <- "C:/repositaries/3.MUVA/MUVA-fwup/data/Follow-up/sample"
infile <- file.path(dir_fp_sample, "sample.rds")


sample <- import(infile)
#data_target <- sample %>% filter(cidade %in% c("Maputo", "Matola", "Beira"))
data_target <- sample %>% filter(provincia = "Maputo Provincia")


```



```{r cars, results='asis', echo=FALSE}



#create list of data.frames  by barrio 

lista <- lapply(split(data_target, data_target$cidade), function(x){
  
  lapply(split(x,x$bairro), function(y){
    y
  })
})


```



```{r,results='asis', echo=FALSE}

for(i in 1:length(lista)){
  
  #start with cidades
  cidades <- names(lista)
  
  for(i in 1:length(lista)){
    
    ciudad <- cidades[i]
    ID_ciudad <- lista[[i]][[1]]$ID_cidade[1]
    
    cat('#',ciudad,' (',ID_ciudad,')',' \n')
    
    bairros <- names(lista[[i]])
    
    for(b in 1:length(bairros)){
      
      bairro <- lista[[i]][[b]]$bairro[1]
      ID_bairro <- lista[[i]][[b]]$ID_bairro[1]
      
      
      cat('##',bairro,' (',ID_bairro, ')',' \n')
      #cat("Coefficients: \n")
      print(knitr::kable(lista[[i]][[b]] %>%
                           select(ID,
                                  participante,
                                  sexo,
                                  quarteirao,
                                  endereco,
                                  referencia,
                                  referencia_proxima,
                                  telefone1,
                                  telefone2
                                  
                                  
                                  
                                  ), row.names = F)) 
      cat("\n")
      cat("\\newpage")
      #cat("Summary: \n")
      cat('\n')
      
    }
    
    
  }
  # 
  # bairro <- lista[[i]]$bairro[1]
  # 
  # 
  # cat('##',bairro,' \n')
  # #cat("Coefficients: \n")
  # print(knitr::kable(lista[[i]], row.names = F)) 
  # cat("\n")
  # cat("\\newpage")
  # #cat("Summary: \n")
  # cat('\n')
}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
